---

- name: Cisco DNAC
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  
  - include_vars: main.yml

  - name: Query DNAC Sites
    cisco.dnac.site_info:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _sites

  - name: Debug DNAC Sites query
    debug:
      var: _sites

  - name: Query DNAC Network
    cisco.dnac.network_info:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _networks

  - name: Debug DNAC Network query
    debug:
      var: _networks

  - name: Query DNAC App Policies
    cisco.dnac.app_policy_info:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _app_policies

  - name: Debug DNAC App Policies query
    debug:
      var: _app_policies

  - name: Query DNAC Discovery
    cisco.dnac.discovery:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _discovery

  - name: Debug DNAC Discovery query
    debug:
      var: _discovery


#   - name: Create DNAC Sites
#     cisco.dnac.site_create:
#       dnac_host: "{{ dnac_host}}"
#       dnac_username: "{{ dnac_username }}"
#       dnac_password: "{{ dnac_password }}"
#       dnac_verify: "{{ dnac_verify }}"
#       dnac_port: "{{ dnac_port }}"
#       dnac_version: "{{ dnac_version }}"
#       dnac_debug: "{{ dnac_debug }}"
#       site:
#         area:
#           name: Portugal
#           parentName: Global
# #   loop: "{{ sites }}"    