---

- name: Cisco DNAC
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  
  - include_vars: main.yml

  - name: Debug start
    debug:
      msg: "Hello"

  - name: Query DNAC Sites
    cisco.dnac.site_create:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: no
      dnac_port: 443
      dnac_version: "2.2.3.3"
      dnac_debug: yes
    register: _sites

  - name: Debug query
    debug:
      var: _sites

#   - name: Create DNAC Sites
#     cisco.dnac.site_create:
#       dnac_host: "{{ dnac_host}}"
#       dnac_username: "{{ dnac_username }}"
#       dnac_password: "{{ dnac_password }}"
#       dnac_verify: no
#       dnac_port: 443
#       dnac_version: "2.2.3.3"
#       dnac_debug: yes
#       site:
#         area:
#           name: Portugal
#           parentName: Global
# #    loop: "{{ sites }}"    