---

- name: Cisco DNAC
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  
  - include_vars: main.yml

  - name: debug
    debug:
      msg: "Hello"

  - name: Create DNAC Site
    cisco.dnac.site_create:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: no
      dnac_port: 443
      dnac_version: "2.2.3.0"
      dnac_debug: yes
      site:
        area:
          name: Portugal
          parentName: Global
#    loop: "{{ sites }}"    