---

- name: Cisco DNAC
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  
  - include_vars: main.yml

  - name: Query DNAC Sites
    cisco.dnac.site_info:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _sites

  - name: Debug DNAC Sites query
    debug:
      var: _sites

  - name: Query DNAC Network
    cisco.dnac.network_info:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _networks

  - name: Debug DNAC Network query
    debug:
      var: _networks

  - name: Query DNAC App Policies
    cisco.dnac.app_policy_info:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _app_policies

  - name: Debug DNAC App Policies query
    debug:
      var: _app_policies

  - name: Query DNAC Device Interfaces query
    cisco.dnac.device_interface_info:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _device_interfaces

  - name: Debug DNAC Device Interfaces query
    debug:
      var: _device_interfaces

  - name: Query DNAC Credentials query
    cisco.dnac.device_credential_info:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _credentials

  - name: Debug DNAC Credentials query
    debug:
      var: _credentials

  - name: Query DNAC Configuration Template query
    cisco.dnac.configuration_template_info:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _configuration_template

  - name: Debug DNAC Configuration Template query
    debug:
      var: _configuration_template

  # - name: Query DNAC Device Details query
  #   cisco.dnac.device_details_info:
  #     dnac_host: "{{ dnac_host}}"
  #     dnac_username: "{{ dnac_username }}"
  #     dnac_password: "{{ dnac_password }}"
  #     dnac_verify: "{{ dnac_verify }}"
  #     dnac_port: "{{ dnac_port }}"
  #     dnac_version: "{{ dnac_version }}"
  #     dnac_debug: "{{ dnac_debug }}"
  #   register: _device_details

  # - name: Debug DNAC Device Details query
  #   debug:
  #     var: _device_details

  # - name: Query DNAC Network Device query
  #   cisco.dnac.network_device_info:
  #     dnac_host: "{{ dnac_host}}"
  #     dnac_username: "{{ dnac_username }}"
  #     dnac_password: "{{ dnac_password }}"
  #     dnac_verify: "{{ dnac_verify }}"
  #     dnac_port: "{{ dnac_port }}"
  #     dnac_version: "{{ dnac_version }}"
  #     dnac_debug: "{{ dnac_debug }}"
  #   register: _network_device

  - name: Debug DNAC Network Device query
    debug:
      var: _network_device

  - name: Query DNAC Wireless Profile query
    cisco.dnac.wireless_profile_info:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _wireless_profile

  - name: Debug DNAC Wireless Profile query
    debug:
      var: _wireless_profile

  - name: Query DNAC Event Subscription query
    cisco.dnac.event_subscription_info:
      dnac_host: "{{ dnac_host}}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
    register: _device_details

  - name: Debug DNAC Event Subscription query
    debug:
      var: _device_details



#   - name: Create DNAC Sites
#     cisco.dnac.site_create:
#       dnac_host: "{{ dnac_host}}"
#       dnac_username: "{{ dnac_username }}"
#       dnac_password: "{{ dnac_password }}"
#       dnac_verify: "{{ dnac_verify }}"
#       dnac_port: "{{ dnac_port }}"
#       dnac_version: "{{ dnac_version }}"
#       dnac_debug: "{{ dnac_debug }}"
#       site:
#         area:
#           name: Portugal
#           parentName: Global
# #   loop: "{{ sites }}"    